--Player Statistics View
CREATE VIEW soccer.All_Players_Stats_Final AS
	SELECT 
		players.name AS "Name",
		players.nationality AS "Nationality", 
		teams.name AS "Team",
		leagues.name AS "League Name",
		player_stats.league_country AS "Country",
		player_stats.games_position AS "Position", 
		players.height AS "Height", 
		players.weight AS "Weight", 
		player_stats.league_season AS "Season",
		player_stats.games_appearences AS "Games Played",
		player_stats.games_lineups AS "Games Started", 
		player_stats.games_minutes AS "Minutes Played",  
		player_stats.games_rating AS "Average Game Rating", 
		player_stats.substitutes_in AS "Substitutions In", 
		player_stats.substitutes_out AS "Substitutions Out", 
		player_stats.shots_total AS "Total Shots", 
		player_stats.shots_on AS "Shots On Target", 
		player_stats.goals_total AS "Total Goals", 
		player_stats.goals_assists AS "Goals Assists", 
		player_stats.goals_conceded AS "Goals Conceded", 
		player_stats.goals_saves AS "Goal Saves", 
		player_stats.passes_total AS "Total Passes", 
		player_stats.passes_key AS "Key Passes", 
		player_stats.passes_accuracy AS "Passes Accuracy %", 
		player_stats.tackles_total AS "Total Tackles", 
		player_stats.tackles_blocks AS "Blocks", 
		player_stats.tackles_interceptions AS "Interceptions", 
		player_stats.duels_total AS "Total Duels", 
		player_stats.duels_won AS "Duels Wons", 
		player_stats.dribbles_attempts AS "Dribble Attempts", 
		player_stats.dribbles_success AS "Dribble Successes", 
		player_stats.fouls_drawn AS "Fouls Drawn", 
		player_stats.fouls_committed AS "Fouls Committed", 
		player_stats.cards_yellow AS  "Yellow Cards", 
		player_stats.cards_yellowred AS "Yellow-Red Cards", 
		player_stats.cards_red AS "Red Cards", 
		player_stats.penalty_won AS "Penalty Won", 
		player_stats.penalty_commited AS "Penalty Committed", 
		player_stats.penalty_scored AS "Penalty Scored", 
		player_stats.penalty_missed AS "Penalty Missed", 
		player_stats.penalty_saved AS "Penalty Saved"
	FROM soccer.players LEFT JOIN soccer.player_stats
	ON
	    soccer.players.id = soccer.player_stats.player_id
	LEFT JOIN soccer.teams
	ON
	    soccer.player_stats.team_id = soccer.teams.id
	LEFT JOIN soccer.leagues 
	ON
	soccer.leagues.id = soccer.teams.league_id
	WHERE soccer.player_stats.games_appearences IS NOT NULL AND soccer.player_stats.games_minutes >= 450
	ORDER BY soccer.player_stats.league_season, soccer.leagues.name, soccer.teams.name, soccer.players.lastname;

--Teams Statistics Views
CREATE VIEW soccer.All_Teams_Stats_Final AS
	SELECT 
		teams.name AS "Team", 
		leagues.name AS "League", 
		leagues.country AS "Country",
		team_statistics.league_season AS "Season",
		team_statistics.fixtures_played_home AS "Home Games",
		team_statistics.fixtures_played_away AS "Away Games",
		team_statistics.fixtures_played_total AS "Total Games",
		team_statistics.fixtures_wins_home AS "Home Wins",
		team_statistics.fixtures_wins_away AS "Away Wins",
		team_statistics.fixtures_wins_total AS "Total Wins",
		team_statistics.fixtures_draws_home AS "Home Draws",
		team_statistics.fixtures_draws_away AS "Away Draws",
		team_statistics.fixtures_draws_total AS "Total Draws",
		team_statistics.fixtures_loses_home AS "Home Losses",
		team_statistics.fixtures_loses_away AS "Away Losses",
		team_statistics.fixtures_loses_total AS "Total Losses",
		team_statistics.goals_for_total_home AS "Total Home Goals",
		team_statistics.goals_for_total_away AS "Total Away Goals",
		team_statistics.goals_for_total_total AS "Total Goals",
		team_statistics.goals_for_average_home AS "Avg Home Goals",
		team_statistics.goals_for_average_away AS "Avg Away Goals",
		team_statistics.goals_for_average_total AS "Avg Goals Total",
		team_statistics."goals_for_minute_0-15_total" AS "Goals For Minute 0-15",
		team_statistics."goals_for_minute_0-15_percentage" AS "% of Goals For Minute 0-15",
		team_statistics."goals_for_minute_16-30_total" AS "Goals For Minute 16-30",
		team_statistics."goals_for_minute_16-30_percentage" AS "% of Goals For Minute 16-30",
		team_statistics."goals_for_minute_31-45_total" AS "Goals For Minute 31-45",
		team_statistics."goals_for_minute_31-45_percentage" AS "% of Goals For Minute 31-45",
		team_statistics."goals_for_minute_46-60_total" AS "Goals For Minute 46-60",
		team_statistics."goals_for_minute_46-60_percentage" AS "% of Goals For Minute 46-60",
		team_statistics."goals_for_minute_61-75_total" AS "Goals For Minute 61-75",
		team_statistics."goals_for_minute_61-75_percentage" AS "% of Goals For Minute 61-75",
		team_statistics."goals_for_minute_76-90_total" AS "Goals For Minute 76-90",
		team_statistics."goals_for_minute_76-90_percentage" AS "% of Goals For Minute 76-90",
		team_statistics."goals_for_minute_91-105_total" AS "Goals For Minute 91-105",
		team_statistics."goals_for_minute_91-105_percentage" AS "% of Goals For Minute 91-105",
		team_statistics."goals_for_minute_106-120_total" AS "Goals For Minute 106-120",
		team_statistics."goals_for_minute_106-120_percentage" AS "% of Goals For Minute 106-120",
		team_statistics.goals_against_total_home AS "Total Home Goals Against",
		team_statistics.goals_against_total_away AS "Total Away Goals Against",
		team_statistics.goals_against_total_total AS "Total Goals Against",
		team_statistics.goals_against_average_home AS "Avg Home Goals Against",
		team_statistics.goals_against_average_away AS "Avg Away Goals Against",
		team_statistics.goals_against_average_total AS "Avg Goals Against Total",
		team_statistics."goals_against_minute_0-15_total" AS "Goals Against Min 0-15",
		team_statistics."goals_against_minute_0-15_percentage" AS "% of Goals Against Minute 0-15",
		team_statistics."goals_against_minute_16-30_total" AS "Goals Against Min 16-30",
		team_statistics."goals_against_minute_16-30_percentage" AS "% of Goals Against Minute 16-30",
		team_statistics."goals_against_minute_31-45_total" AS "Goals Against Min 31-45",
		team_statistics."goals_against_minute_31-45_percentage" AS "% of Goals Against Minute 31-45",
		team_statistics."goals_against_minute_46-60_total" AS "Goals Against Min 46-60",
		team_statistics."goals_against_minute_46-60_percentage" AS "% of Goals Against Minute 46-60",
		team_statistics."goals_against_minute_61-75_total" AS "Goals Against Min 61-75",
		team_statistics."goals_against_minute_61-75_percentage" AS "% of Goals Against Minute 61-75",
		team_statistics."goals_against_minute_76-90_total" AS "Goals Against Min 76-90",
		team_statistics."goals_against_minute_76-90_percentage" AS "% of Goals Against Minute 76-90",
		team_statistics."goals_against_minute_91-105_total" AS "Goals Against Min 91-105",
		team_statistics."goals_against_minute_91-105_percentage" AS "% of Goals Against Minute 91-105",
		team_statistics."goals_against_minute_106-120_total" AS "Goals Against Min 106-120",
		team_statistics."goals_against_minute_106-120_percentage" AS "% of Goals Against Minute 106-120",
		team_statistics.biggest_streak_wins AS "Longest Win Streak",
		team_statistics.biggest_streak_draws AS "Longest Draw Streak",
		team_statistics.biggest_streak_loses AS "Longest Losing Streak",
		team_statistics.biggest_wins_home AS "Biggest Home Win",
		team_statistics.biggest_wins_away AS "Biggest Away Win",
		team_statistics.biggest_loses_home As "Biggest Home Loss",
		team_statistics.biggest_loses_away AS "Biggest Away Loss",
		team_statistics.biggest_goals_for_home AS "Most Home Goals",
		team_statistics.biggest_goals_for_away AS "Most Away Goals",
		team_statistics.biggest_goals_against_home AS "Most Home Goals Against",
		team_statistics.biggest_goals_against_away AS "Most Away Goals Against",
		team_statistics.clean_sheet_home AS "Home Clean Sheets",
		team_statistics.clean_sheet_away AS "Away Clean Sheets",
		team_statistics.clean_sheet_total AS "Total Clean Sheets",
		team_statistics.failed_to_score_home AS "Failed to Score Home",
		team_statistics.failed_to_score_away AS "Failed to Score Away",
		team_statistics.failed_to_score_total AS "Total Games Failed to Score",
		team_statistics.penalty_scored_total AS "Total Penalty Scored",
		team_statistics.penalty_scored_percentage AS  "% Penalty Scored",
		team_statistics.penalty_missed_total AS "Total Penalty Missed",
		team_statistics.penalty_missed_percentage AS "% Penalty Missed",
		team_statistics.penalty_total AS "Total Penalties",
		team_statistics."cards_yellow_0-15_total" AS "Yellow Card Minute 0-15",
		team_statistics."cards_yellow_0-15_percentage" AS "% Yellow Card Minute 0-15",
		team_statistics."cards_yellow_16-30_total" AS "Yellow Card Minute 16-30",
		team_statistics."cards_yellow_16-30_percentage" AS "% Yellow Card Minute 16-30",
		team_statistics."cards_yellow_31-45_total" AS "Yellow Card Minute 31-45",
		team_statistics."cards_yellow_31-45_percentage" AS "% Yellow Card Minute 31-45",
		team_statistics."cards_yellow_46-60_total" AS "Yellow Card Minute 46-60",
		team_statistics."cards_yellow_46-60_percentage" AS "% Yellow Card Minute 46-60",
		team_statistics."cards_yellow_61-75_total" AS "Yellow Card Minute 61-75",
		team_statistics."cards_yellow_61-75_percentage" AS "% Yellow Card Minute 61-75",
		team_statistics."cards_yellow_76-90_total" AS "Yellow Card Minute 76-90",
		team_statistics."cards_yellow_76-90_percentage" AS "% Yellow Card Minute 76-90",
		team_statistics."cards_yellow_91-105_total" AS "Yellow Card Minute 91-105",
		team_statistics."cards_yellow_91-105_percentage" AS "% Yellow Card Minute 91-105",
		team_statistics."cards_yellow_106-120_total" AS "Yellow Card Minute 106-120",
		team_statistics."cards_yellow_106-120_percentage" AS "% Yellow Card Minute 106-120",
		team_statistics."cards_red_0-15_total" AS "Red Card Minute 0-15",
		team_statistics."cards_red_0-15_percentage" AS "% Red Card Minute 0-15",
		team_statistics."cards_red_16-30_total" AS "Red Card Minute 16-30",
		team_statistics."cards_red_16-30_percentage" AS "% Red Card Minute 16-30",
		team_statistics."cards_red_31-45_total" AS "Red Card Minute 31-45",
		team_statistics."cards_red_31-45_percentage" AS "% Red Card Minute 31-45",
		team_statistics."cards_red_46-60_total" AS "Red Card Minute 46-60",
		team_statistics."cards_red_46-60_percentage" AS "% Red Card Minute 46-60",
		team_statistics."cards_red_61-75_total" AS "Red Card Minute 61-75",
		team_statistics."cards_red_61-75_percentage" AS "% Red Card Minute 61-75",
		team_statistics."cards_red_76-90_total" AS "Red Card Minute 76-90",
		team_statistics."cards_red_76-90_percentage" AS "% Red Card Minute 76-90",
		team_statistics."cards_red_91-105_total" AS "Red Card Minute 91-105",
		team_statistics."cards_red_91-105_percentage" AS "% Red Card Minute 91-105",
		team_statistics."cards_red_106-120_total" AS "Red Card Minute 106-120",
		team_statistics."cards_red_106-120_percentage" AS "% Red Card Minute 106-120"	
	FROM soccer.teams LEFT JOIN soccer.leagues 
	ON
		soccer.teams.league_id = soccer.leagues.id
	LEFT JOIN soccer.team_statistics
	ON
		soccer.teams.id = soccer.team_statistics.team_id
	ORDER BY soccer.team_statistics.league_season, soccer.leagues.country, soccer.leagues.name, soccer.teams.name;