version: '3.8'

services:
  pg_football:
    environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ./warehouse/soccer_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: always
    image: postgres:13
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on: 
      - pg_football
    ports:
      - "8080:80"
  pythonapp:
    build: ./
    command: sh -c "sleep 20s && cd code/soccer && python soccer_leagues.py --year 2021"
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DB=${POSTGRES_DB}
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
    depends_on:
      - pg_football
  # dashboard:
  #   image: metabase/metabase
  #   container_name: dashboard
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./matabase-data:/metabase-data
  #   environment:
  #     - MB_DB_FILE=/metabase-data/metabase.db
  #   depends_on:
  #     - pythonapp