version: '3.8'

services:
  pgdatabase:
    environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ./warehouse/soccer_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: always
    image: postgres:13
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on: 
      - pgdatabase
    ports:
      - "8080:80"
  pythonapp:
    build: ./
    command: sh -c "sleep 20s && cd code/soccer && python soccer_leagues.py --year 2019"
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DB=${POSTGRES_DB}
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
    depends_on:
      - pgdatabase
  dashboard:
    image: metabase/metabase
    container_name: dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db